grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    scoring: 'accuracy'
    n_jobs: -1
    verbose: 3

model_selection:

  # Decision Tree Classifier parameters
  dtc:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      criterion: gini
      max_depth: 10
      min_samples_split: 10
      min_samples_leaf: 2
    search_param_grid:
      criterion:
        - log_loss
        - entropy
      max_depth:
        - 20
        - 30
      max_features:
        - log2
        - sqrt
      min_samples_split:
        - 15
        - 20



  # Random Forest Classifier parameters
  rfc:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 10
      min_samples_leaf: 2
    search_param_grid:
      criterion:
        - gini
        - entropy
      n_estimators:
        - 200
        - 300
      max_depth:
        - 50
        - 60
      max_features:
        - sqrt
        - log2
      min_samples_split:
        - 10
        - 15
      min_samples_leaf:
        - 2
        - 4
      bootstrap:
        - true
      class_weight:
        - {0: 1, 1: 2}


  # Gradient Boosting Classifier parameters
  gb:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 50
      learning_rate: 0.01
      max_depth: 3
    search_param_grid:
      n_estimators:
        - 200
      learning_rate:
        - 0.5
        - 0.3
      min_samples_leaf:
        - 2
        - 3
      min_samples_split:
        - 5
        - 10
      subsample:
        - 0.5
        - 0.8
      loss:
        - exponential
        - log_loss


  # XGBoost Classifier parameters
  xgb:
    class: XGBClassifier
    module: xgboost
    params:
      n_estimators: 100
      learning_rate: 0.01
      max_depth: 3
    search_param_grid:
      n_estimators:
        - 100
        - 200
      learning_rate:
        - 0.2
        - 0.1
      max_depth:
        - 10
        - 15
      subsample:
        - 0.8
        - 1.0
      colsample_bytree:
        - 0.5
        - 0.7
      gamma:
        - 0.1
      reg_alpha:
        - 1.5
      reg_lambda:
        - 1.0

